# Backend related ports are commented out, comment them back in if needed during development

# Networks for backend and database are separated
networks:
 backend: 
   external: false
 database: 
   external: false

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
#      - "3000:3000" # TODO: label this
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}" # primary user access, defaults to 5173
#    expose:
#      - '3000' # TODO: label this
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
      - VITE_BACKEND_URL=http://backend:5000
      - VITE_PORT=${VITE_PORT}
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - backend


  backend:
    container_name: backend
    build: ./backend
#    ports:
#      - "5000:5000" # Communication with frontend
    expose:
      - "5000" # Communication with frontend
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_URL=bolt://neo4j:7687
      - DB_NAME=neo4j
      - DB_USERNAME=neo4j #locked to 'neo4j' in community version
      - DB_PASSWORD=${DB_PASSWORD}
      - OPENAI_KEY=${OPENAI_KEY}
      - VITE_PORT=${VITE_PORT}
    depends_on:
      neo4j:
        
        condition: service_healthy
    networks:
      - backend
      - database
    healthcheck:
      #test: ["CMD", "nc", "-z", "localhost", "5000"] # check if port is open
      test: ["CMD", "nc", "-z", "backend", "5000"] # check if port is open
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s


  neo4j:
    container_name: neo4j
    image: neo4j:5.25-community
    # ports:
    #   - "7474:7474" # For admin interface access through browser
    #   - "7687:7687" # bolt communication
    expose:
      - "7687" # Communication with backend
    environment:
      - NEO4J_initial.dbms.default_database=neo4j
      #- NEO4J_ACCEPT_LICENSE_AGREEMENT=yes # only needed for enterprise version
      - NEO4J_AUTH=neo4j/${DB_PASSWORD}
      # memory setup for "light weight application"
      - NEO4J_server.dbms.usage_report.enabled=false # disables anonymouse usage data https://neo4j.com/docs/reference/usage-data/
      - NEO4J_server.memory.heap.initial_size=512M  # Initial heap size
      - NEO4J_server.memory.heap.max_size=1G  # Max heap size
      - NEO4J_server.memory.pagecache.size=512M  # Page cache size
      - NEO4J_db.memory.transaction.max=256M  # Max memory per transaction
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "${DB_PASSWORD}", "CALL db.ping()"]
      interval: 10s
      retries: 5
    volumes:
      - neo4j_data:/data   # Persist database data
      - neo4j_logs:/logs   # Persist logs
      - neo4j_plugins:/plugins  # Directory for plugins (optional)
    networks:
      - database

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins: