# Backend related ports are commented out, comment them back in if needed during development

# Networks for backend and frontend are separated
networks:
 backend: 
   external: false
 database: 
   external: false

services:
  frontend:
    build: ./frontend
    ports:
#      - "3000:3000"
      - "5173:5173" # primary user access to application
    expose:
#      - '3000' # TODO: label this
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - backend


  backend:
    build: ./backend
#    ports:
#      - "5000:5000"
    expose:
      - "5000" # Communication with frontend
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - NEO4J_URL=${NEO4J_URL}
      - NEO4J_DB_NAME=${NEO4J_DB_NAME}
      - NEO4J_USERNAME=neo4j #locked to 'neo4j' in community version
      - NEO4J_USERPASSWORD=${NEO4J_USERPASSWORD}
      - OPENAI_KEY=${OPENAI_KEY}
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - backend
      - database
    healthcheck:
      #test: ["CMD", "nc", "-z", "host.docker.internal", "5000"] # check if port is open
      test: ["CMD", "nc", "-z", "backend", "5000"] # check if port is open
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s


  neo4j:
    image: neo4j:5.25-community
#    ports:
      #- "7433:7433" #changed from normal 7474 because of conflict somewhere. Only for admin interface access.
#      - "7687:7687"
    expose:
      - "7687" # Communication with backend
    environment:
      #- NEO4J_ACCEPT_LICENSE_AGREEMENT=yes # possibly only needed for enterprise version
      - NEO4J_AUTH=neo4j/${NEO4J_USERPASSWORD}
      # memory setup for "light weight application"
      - NEO4J_server.memory.heap.initial_size=512M  # Initial heap size
      - NEO4J_server.memory.heap.max_size=1G  # Max heap size
      - NEO4J_server.memory.pagecache.size=512M  # Page cache size
      - NEO4J_db.memory.transaction.max=256M  # Max memory per transaction
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "${NEO4J_USERPASSWORD}", "CALL db.ping()"]
      interval: 10s
      retries: 5
    volumes:
      - neo4j_data:/data   # Persist database data
      - neo4j_logs:/logs   # Persist logs
      - neo4j_plugins:/plugins  # Directory for plugins (optional)
    networks:
      - database

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins: