site_name: CED-LLM Documentation
docs_dir: app/docs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
          paths:
            - backend/app

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlitght
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright:
  '&copy; 2024 <a href="https://github.com/ProjectCED" target="_blank" rel="noopener">ProjectCED</a>'