name: ci
on:
  push:
    branches:
      - master
      - main
      - backend-documentation
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocstrings
        working-directory: ./backend

      - name: Build MkDocs site
        run: mkdocs build
        working-directory: ./backend

      - name: Move site to docs directory
        run: mv backend/site docs


      - name: Create .nojekyll file
        run: echo "" > backend/site/.nojekyll
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./backend/site
          publish_branch: main
